{{- if .Values.inventoryServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensor-monitoring.fullname" . }}-inventory
  labels:
    {{- include "sensor-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: inventory
spec:
  replicas: {{ .Values.inventoryServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "sensor-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: inventory
  template:
    metadata:
      labels:
        {{- include "sensor-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: inventory
    spec:
      containers:
      - name: inventory
        image: "{{ .Values.inventoryServer.image.repository }}:{{ .Values.inventoryServer.image.tag }}"
        imagePullPolicy: {{ .Values.inventoryServer.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 1337
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /inventory
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /inventory
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.inventoryServer.resources | nindent 10 }}
{{- end }}

