{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensor-monitoring.fullname" . }}-prometheus
  labels:
    {{- include "sensor-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.prometheus.service.type "NodePort" }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
    {{- end }}
  selector:
    {{- include "sensor-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}

