{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sensor-monitoring.fullname" . }}-targets
  labels:
    {{- include "sensor-monitoring.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if and .Values.prometheus.enabled .Values.prometheus.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sensor-monitoring.fullname" . }}-prometheus-data
  labels:
    {{- include "sensor-monitoring.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.prometheus.storage.storageClass }}
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
{{- end }}

